"""empty message

Revision ID: 40529d462aee
Revises: 
Create Date: 2020-03-28 11:15:20.821112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40529d462aee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('userimage', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userprofile_username'), 'userprofile', ['username'], unique=True)
    op.drop_index('ix_UserProfile_userName', table_name='UserProfile')
    op.drop_table('UserProfile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserProfile',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"UserProfile_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('userName', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('userImage', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='UserProfile_pkey')
    )
    op.create_index('ix_UserProfile_userName', 'UserProfile', ['userName'], unique=True)
    op.drop_index(op.f('ix_userprofile_username'), table_name='userprofile')
    op.drop_table('userprofile')
    # ### end Alembic commands ###
